### ISSUE TITLE
options.mode crop does not work

### ISSUE THREAD

**Issue by dalmer** [bertramdev/selfie#11]
File: ImageResizer.groovy

On crop mode the image passed to the Scalr.crop method will always be null.

this line

```outputImage = Scalr.crop(outputImage,options.x ?: 0,options.y ?: 0, options.width, options.height, Scalr.OP_ANTIALIAS)```

I think was meant to be

```outputImage = Scalr.crop(image,options.x ?: 0,options.y ?: 0, options.width, options.height, Scalr.OP_ANTIALIAS)```

since outputImage is initialized as null

**Comment by davydotcom** [comment]
great catch. Will fix
