### ISSUE TITLE
I cannot find a way to set the baseUrl based on the configuration

### ISSUE THREAD

**Issue by alexboly** [bertramdev/selfie#13]
I'd like to have the baseUrl using localhost for dev and the real url for staging and production. I tried using the grails.serverURL property, but it doesn't work - probably it's not set yet.

I'm working with grails 2.5, selfie 0.3.0.

Thanks!

**Comment by davydotcom** [comment]
if using a local storage provider you set this on the localProvider.. here is an example local config

```
	selfie {
	  storage {
		bucket = 'uploads'
		providerOptions {
		  provider = 'local'
		  basePath = './workspace'
		  baseUrl = 'http://localhost:8080/storage'
		}
	  }
	}
```

**Comment by davydotcom** [comment]
Also to serve files from your local you have to turn on karman's local storage controller

```
karman {
	  serveLocalStorage = true
	  serveLocalMapping = 'storage' // means /storage is base path
	  storagePath = 'workspace'
}
```

**Comment by alexboly** [comment]
Thanks! In the meantime, I found a way: I created a new grails environment called staging and I'm setting the right path per environment.
