### ISSUE TITLE
 unable to resolve class org.hibernate.engine.SessionImplementor

### ISSUE THREAD

**Issue by juljanmay** [bertramdev/selfie#2]
I tried to add to plugins
compile ':selfie:0.1.0' as well as
compile ':selfie:0.2.0'

but both give me the following error when I try to refresh dependencies. I also added "mavenRepo 'http://dl.bintray.com/karman/karman'" to the repositories.

plugins\selfie-0.1.0\src\groovy\com\bertramlabs\plugins\selfie\AttachmentUserType.groovy: 10: unable to resolve class org.hibernate.engine.SessionImplementor

What am I missing?

**Comment by davydotcom** [comment]
no longer an issue
