### ISSUE TITLE
example in doc

### ISSUE THREAD

**Issue by fcavola** [bertramdev/selfie#3]
Hello, in the example you define:
Attachment photo

and in PhotoController the domain class Photo:
def photo = new Photo(params)

To try it i have to define a new domain class Photo?

Francesco

**Comment by robokaso** [comment]
Following the docs I can't make the basic picture upload example work either... could you add a working testcase or a demo project?

**Comment by davydotcom** [comment]
Sure thing i have one somewhere around here, if you want to paste what your domain model looks like i can probably figure out what sup

**Comment by robokaso** [comment]
It's basically a copy-paste of the docs, but here it is... using grails 2.5.0, selfie 0.5.0

Controller:
```
import grails.converters.JSON

class ExampleController {

    def upload() {
        def example = new Example(params)

        if(!example.save()) {
            println "Error Saving! ${example.errors.allErrors}"
        }
        redirect controller: 'example', action: 'list'
    }

    def list() {
        def photos = Example.list()
        render photos as JSON
    }
}
```
Domain:
```
import com.bertramlabs.plugins.selfie.Attachment

class Example {

    String name

    Attachment photo

    static attachmentOptions = [
            photo: [
                    styles: [
                            thumb: [width: 50, height: 50, mode: 'fit'],
                            medium: [width: 250, height: 250, mode: 'scale']
                    ]
            ]
    ]

    static embedded = ['photo'] //required

    static constraints = {
        photo contentType: ['png','jpg'], fileSize:1024*1024 // 1mb
    }
}
```
View:
```
<g:uploadForm name="upload" url="[action:'upload',controller:'example']">
  <g:textField name="name" placeholder="name"/><br/>
  <input type="file" name="photo" /><br/>
  <g:submitButton name="update" value="Update" /><br/>
</g:uploadForm>
```
Config:
```
grails {
	plugin {
		karman {
			serveLocalStorage = true
			serveLocalMapping = 'storage' // means /storage is base path
			storagePath = 'storage'
		}
		selfie {
			storage {
				bucket = 'uploads'
				providerOptions {
					provider = 'local' // Switch to s3 if you wish to use s3 and install the karman-aws plugin
					basePath = 'storage'
					baseUrl  = 'http://localhost:8090/image-test/storage'
					//accessKey = "KEY" //Used for S3 Provider
					//secretKey = "KEY" //Used for S3 Provider
				}
			}
		}
	}
}
```
Resulting Error:
```
Validation Error(s) occurred during save(): 
- Field error in object 'com.etherapia.portal.Example' on field 'photo': 
rejected value [com.bertramlabs.plugins.selfie.Attachment@3aae08ab]; 
codes [Example.photo.contentType.errorExample.photo,Example.photo.contentType.error.photo,Example.photo.contentType.error.com.bertramlabs.plugins.selfie.Attachment,Example.photo.contentType.error,example.photo.contentType.error.Example.photo,example.photo.contentType.error.photo,example.photo.contentType.error.com.bertramlabs.plugins.selfie.Attachment,example.photo.contentType.error,photo.contentType.Example.photo,photo.contentType.invalid.photo,Example.photo.contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,Example.photo.contentType.invalid,example.photo.contentType.invalid.photo,example.photo.contentType.invalid.photo,example.photo.contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,example.photo.contentType.invalid,contentType.invalid.cExample.photo,contentType.invalid.photo,contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,contentType.invalid]; arguments [photo,class Example,image/jpeg]; 
default message [null] 
```

**Comment by davydotcom** [comment]
try removing the contentType constraint 
--
David Estes

On April 8, 2015 at 10:28:59 AM, Robert Kasanický (notifications@github.com) wrote:

It's basically a copy-paste of the docs, but here it is... using grails 2.5.0, selfie 0.5.0

Controller:

import grails.converters.JSON

class ExampleController {

    def upload() {
        def example = new Example(params)

        if(!example.save()) {
            println "Error Saving! ${example.errors.allErrors}"
        }
        redirect controller: 'example', action: 'list'
    }

    def list() {
        def photos = Example.list()
        render photos as JSON
    }
}

Domain:

import com.bertramlabs.plugins.selfie.Attachment

class Example {

    String name

    Attachment photo

    static attachmentOptions = [
            photo: [
                    styles: [
                            thumb: [width: 50, height: 50, mode: 'fit'],
                            medium: [width: 250, height: 250, mode: 'scale']
                    ]
            ]
    ]

    static embedded = ['photo'] //required

    static constraints = {
        photo contentType: ['png','jpg'], fileSize:1024*1024 // 1mb
    }
}

View:

<g:uploadForm name="upload" url="[action:'upload',controller:'example']">
  <g:textField name="name" placeholder="name"/><br/>
  <input type="file" name="photo" /><br/>
  <g:submitButton name="update" value="Update" /><br/>
</g:uploadForm>

Config:

grails {
    plugin {
        karman {
            serveLocalStorage = true
            serveLocalMapping = 'storage' // means /storage is base path
            storagePath = 'storage'
        }
        selfie {
            storage {
                bucket = 'uploads'
                providerOptions {
                    provider = 'local' // Switch to s3 if you wish to use s3 and install the karman-aws plugin
                    basePath = 'storage'
                    baseUrl  = 'http://localhost:8090/image-test/storage'
                    //accessKey = "KEY" //Used for S3 Provider
                    //secretKey = "KEY" //Used for S3 Provider
                }
            }
        }
    }
}

Resulting Error:

Validation Error(s) occurred during save():  
- Field error in object 'com.etherapia.portal.Example' on field 'photo':  
rejected value [com.bertramlabs.plugins.selfie.Attachment@3aae08ab];  
codes [Example.photo.contentType.errorExample.photo,Example.photo.contentType.error.photo,Example.photo.contentType.error.com.bertramlabs.plugins.selfie.Attachment,Example.photo.contentType.error,example.photo.contentType.error.Example.photo,example.photo.contentType.error.photo,example.photo.contentType.error.com.bertramlabs.plugins.selfie.Attachment,example.photo.contentType.error,photo.contentType.Example.photo,photo.contentType.invalid.photo,Example.photo.contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,Example.photo.contentType.invalid,example.photo.contentType.invalid.photo,example.photo.contentType.invalid.photo,example.photo.contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,example.photo.contentType.invalid,contentType.invalid.cExample.photo,contentType.invalid.photo,contentType.invalid.com.bertramlabs.plugins.selfie.Attachment,contentType.invalid]; arguments [photo,class Example,image/jpeg];  
default message [null]

**Comment by robokaso** [comment]
removing the constraint worked, thanks.

(btw. the images I used for testing were below the fileSize limit but I that's a topic for a separate issue I guess)

**Comment by davydotcom** [comment]
I think the constraint needs fixed for the embedded object type is why. Ill look into fixing that today. Thanks for finding that
--
David Estes

On April 8, 2015 at 10:44:19 AM, Robert Kasanický (notifications@github.com) wrote:

removing the constraint worked, thanks.

(btw. the images I used for testing were below the fileSize limit but I that's a topic for a separate issue I guess)
