### ISSUE TITLE
Can't find dependency

### ISSUE THREAD

**Issue by naman90** [bertramdev/selfie#7]
I am trying to use the plugin according to the docs. It's throwing this error.
Error |
Resolve error obtaining dependencies: Could not find artifact com.bertramlabs.plugins:karman-core:jar:0.5.3 in dl_bintray_com_karman_karman (http://dl.bintray.com/karman/karman)

**Comment by max-krueper** [comment]
Use:

compile ":selfie:0.5.0"

**Comment by davydotcom** [comment]
Yep bump the version up. Karman is now in maven central in version 0.6.1 had to loose previous versions to move it in bintray

**Comment by naman90** [comment]
Thanks.
